[test]
root = "./tests/unit"
preload = ["./tests/unit/setup.ts"]

[resolve.alias]
"@" = "../.."
"server-only" = "./tests/unit/mocks/server-only.ts"
"next/navigation" = "./tests/unit/mocks/next-navigation.ts"
"next/navigation.js" = "./tests/unit/mocks/next-navigation.ts"
