/**
 * Generates JavaScript code that will be executed inside the sandbox.
 * These scripts set up the sandbox environment, API bridges, and user code execution.
 */

import { SANDBOX_CONFIG } from './config';
import type { LocationHints } from './api-bridge';

/**
 * Creates the bootstrap script that sets up the sandbox environment
 */
export function createBootstrapScript(): string {
  return [
    '"use strict";',
    '',
    '// Initialize stdout and stderr capture',
    'const __virid_stdout__ = [];',
    'const __virid_stderr__ = [];',
    '',
    '// Format function for console output',
    'function __virid_format__(value) {',
    '  if (value === null || value === undefined) return String(value);',
    '  if (typeof value === "string") return value;',
    '  if (typeof value === "object") {',
    '    try {',
    '      return JSON.stringify(value);',
    '    } catch {',
    '      return "[object]";',
    '    }',
    '  }',
    '  return String(value);',
    '}',
    '',
    '// Initialize result container',
    'globalThis.__virid_last_result__ = { status: "ok", value: undefined };',
    'globalThis.__virid_stdout__ = __virid_stdout__;',
    'globalThis.__virid_stderr__ = __virid_stderr__;',
    '',
    '// Override console methods to capture output',
    'globalThis.console = Object.freeze({',
    '  log: (...args) => __virid_stdout__.push(args.map(__virid_format__).join(" ")),',
    '  info: (...args) => __virid_stdout__.push(args.map(__virid_format__).join(" ")),',
    '  warn: (...args) => __virid_stdout__.push(args.map(__virid_format__).join(" ")),',
    '  error: (...args) => __virid_stderr__.push(args.map(__virid_format__).join(" ")),',
    '});',
  ].join('\n');
}

/**
 * Creates the API script that exposes external services to the sandbox
 */
export function createApiScript(locationHints: LocationHints | null): string {
  const hintsLiteral = locationHints ? JSON.stringify(locationHints) : 'null';

  return [
    '(function () {',
    '  "use strict";',
    '',
    `  const hints = ${hintsLiteral};`,
    '  const hostGetWeather = globalThis.__virid_host_get_weather__;',
    '',
    '  // Utility functions',
    '  function coerceFiniteNumber(value) {',
    '    if (typeof value === "number") {',
    '      return Number.isFinite(value) ? value : null;',
    '    }',
    '    if (typeof value === "string") {',
    '      const trimmed = value.trim();',
    '      if (trimmed.length === 0) return null;',
    '      const parsed = Number.parseFloat(trimmed);',
    '      return Number.isFinite(parsed) ? parsed : null;',
    '    }',
    '    return null;',
    '  }',
    '',
    '  function validateCoordinates(coords) {',
    '    if (!coords || typeof coords !== "object") return null;',
    '    const latitude = coerceFiniteNumber(coords.latitude);',
    '    const longitude = coerceFiniteNumber(coords.longitude);',
    '    if (latitude === null || longitude === null) return null;',
    '    if (latitude < -90 || latitude > 90) return null;',
    '    if (longitude < -180 || longitude > 180) return null;',
    '    return { latitude, longitude };',
    '  }',
    '',
    '  // Create the API object',
    '  const api = Object.freeze({',
    '',
    '    /**',
    '     * Fetch data from external URLs',
    '     * @param {string} url - The URL to fetch',
    '     * @param {RequestInit} [options] - Fetch options',
    '     * @returns {Promise<Response>} The fetch response',
    '     */',
    '    async fetch(url, options = {}) {',
    '      if (typeof url !== "string" || url.length === 0) {',
    '        throw new TypeError("URL must be a non-empty string");',
    '      }',
    '      // In QuickJS, fetch is not available by default',
    '      // This is a placeholder for future implementation',
    '      throw new Error("fetch is not yet available in this sandbox");',
    '    },',
    '',
    '    /**',
    '     * Get weather data for specific coordinates',
    '     * @param {Object} coordinates - The coordinates',
    '     * @param {number} coordinates.latitude - Latitude (-90 to 90)',
    '     * @param {number} coordinates.longitude - Longitude (-180 to 180)',
    '     * @returns {Promise<Object>} Weather data from Open-Meteo',
    '     */',
    '    async getWeather(coordinates) {',
    '      if (typeof hostGetWeather !== "function") {',
    '        throw new Error("Weather API is unavailable in this context");',
    '      }',
    '',
    '      const validated = validateCoordinates(coordinates);',
    '      if (!validated) {',
    '        throw new TypeError(',
    '          "Invalid coordinates: latitude must be -90 to 90, longitude must be -180 to 180"',
    '        );',
    '      }',
    '',
    '      const payload = JSON.stringify(validated);',
    '      const responseText = await hostGetWeather(payload);',
    '      return JSON.parse(responseText);',
    '    },',
    '  });',
    '',
    '  // Expose API globally',
    '  globalThis.api = api;',
    '})();',
  ].join('\n');
}

/**
 * Creates the execution wrapper script for user code
 */
export function createExecutionScript(code: string): string {
  return [
    '"use strict";',
    '',
    '(async function () {',
    '  const api = globalThis.api;',
    '',
    '  try {',
    '    const result = await (async function __virid_user_entry__() {',
    code,
    '    })();',
    '',
    '    globalThis.__virid_last_result__ = { status: "ok", value: result };',
    '  } catch (error) {',
    '    globalThis.__virid_last_result__ = {',
    '      status: "error",',
    '      error: {',
    '        name: error && error.name ? String(error.name) : "Error",',
    '        message: error && error.message ? String(error.message) : String(error),',
    '        stack: error && error.stack ? String(error.stack) : null,',
    '      },',
    '    };',
    '  }',
    '})();',
  ].join('\n');
}

/**
 * Creates the summary script that collects execution results
 */
export function createSummaryScript(): string {
  return [
    '(function () {',
    '  "use strict";',
    '',
    '  const seen = new WeakSet();',
    `  const limit = ${SANDBOX_CONFIG.MAX_COLLECTION_ITEMS};`,
    `  const maxDepth = ${SANDBOX_CONFIG.MAX_SERIALIZATION_DEPTH};`,
    '',
    '  function sanitize(value, depth) {',
    '    if (depth > maxDepth) {',
    '      return "[max-depth]";',
    '    }',
    '',
    '    // Handle primitives',
    '    if (value === null) return null;',
    '    if (value === undefined) return null;',
    '    if (typeof value === "string") return value;',
    '    if (typeof value === "number") return value;',
    '    if (typeof value === "boolean") return value;',
    '    if (typeof value === "bigint") return Number(value);',
    '',
    '    if (typeof value === "function") {',
    '      return `[function ${' + "value.name || 'anonymous'" + '}]`;',
    '    }',
    '',
    '    if (value instanceof Date) {',
    '      return value.toISOString();',
    '    }',
    '',
    '    // Handle circular references',
    '    if (seen.has(value)) {',
    '      return "[circular]";',
    '    }',
    '    seen.add(value);',
    '',
    '    // Handle arrays',
    '    if (Array.isArray(value)) {',
    '      const slice = value.slice(0, limit).map((entry) => sanitize(entry, depth + 1));',
    '      if (value.length > limit) {',
    '        slice.push(`[+${' + 'value.length - limit' + '} more]`);',
    '      }',
    '      seen.delete(value);',
    '      return slice;',
    '    }',
    '',
    '    // Handle objects',
    '    const entries = Object.entries(value);',
    '    const result = {};',
    '    for (let index = 0; index < entries.length && index < limit; index += 1) {',
    '      const [key, entryValue] = entries[index];',
    '      result[key] = sanitize(entryValue, depth + 1);',
    '    }',
    '    if (entries.length > limit) {',
    '      result.__truncated__ = entries.length - limit;',
    '    }',
    '    seen.delete(value);',
    '    return result;',
    '  }',
    '',
    '  const base = globalThis.__virid_last_result__ || { status: "ok", value: undefined };',
    '  const stdout = Array.isArray(globalThis.__virid_stdout__) ? globalThis.__virid_stdout__ : [];',
    '  const stderr = Array.isArray(globalThis.__virid_stderr__) ? globalThis.__virid_stderr__ : [];',
    '',
    `  const stdoutSlice = stdout.slice(0, ${SANDBOX_CONFIG.MAX_LOG_LINES});`,
    `  const stderrSlice = stderr.slice(0, ${SANDBOX_CONFIG.MAX_LOG_LINES});`,
    '',
    '  const payload = {',
    '    status: base.status === "error" ? "error" : "ok",',
    '    value: base.status === "error" ? null : sanitize(base.value, 0),',
    '    error: base.status === "error" ? sanitize(base.error || { message: "Unknown error" }, 0) : null,',
    '    stdout: stdoutSlice,',
    '    stderr: stderrSlice,',
    '    truncatedStdout: Math.max(stdout.length - stdoutSlice.length, 0),',
    '    truncatedStderr: Math.max(stderr.length - stderrSlice.length, 0),',
    '  };',
    '',
    '  return JSON.stringify(payload);',
    '})()',
  ].join('\n');
}
